[workspace]
channels = ["conda-forge", "bioconda"]
name = "gnomad_api_cache"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.7,<3.15"

[pypi-dependencies]
gnomad-api-cache = { path = ".", editable = true }

# Dev-only tools.
[feature.dev.pypi-dependencies]
ipykernel = ">=7.3.0,<8"
pandas = ">=3.0.5,<4"

[environments]
default = { features = [], solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
